FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Build args for NEXT_PUBLIC_ variables
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_VAPI_WORKFLOW_ID
ARG NEXT_PUBLIC_VAPI_WEB_TOKEN

# Make them available during build
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_VAPI_WORKFLOW_ID=$NEXT_PUBLIC_VAPI_WORKFLOW_ID
ENV NEXT_PUBLIC_VAPI_WEB_TOKEN=$NEXT_PUBLIC_VAPI_WEB_TOKEN

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]