apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview-app
  template:
    metadata:
      labels:
        app: interview-app
    spec:
      containers:
        - name: interview-app
          image: docker.io/library/interview-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: interview-secrets